# -*- coding: utf-8 -*-
"""스트리밍 알고리즘 비교 실험.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLnAWfvk9DS0oJ2iJU7TheG-7qyAIA_Q
"""

"""
스트리밍 알고리즘 구현
빅데이터분석 과제 4
알고리즘: Bloom Filter + Count-Min Sketch
데이터셋: MovieLens 스타일 이벤트 스트림 (200,000개 레코드)
"""

import csv, math, random, time, sys, hashlib, json
from collections import defaultdict

random.seed(42)


# ══════════════════════════════════════════════════════════════════════
# 데이터셋 생성 (한 번만 실행하여 events.csv 생성)
# ══════════════════════════════════════════════════════════════════════
def generate_dataset(filename="events.csv", n=200_000):
    movies  = [f"movie_{i}" for i in range(1, 4000)]
    users   = [f"user_{i}"  for i in range(1, 10000)]
    actions = ["view", "rate", "like", "skip", "watchlist"]

    with open(filename, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["event_id", "user_id", "movie_id", "action", "rating"])
        for i in range(n):
            uid    = random.choices(users,  weights=[1/(j+1) for j in range(len(users))])[0]
            mid    = random.choices(movies, weights=[1/(j+1) for j in range(len(movies))])[0]
            act    = random.choices(actions, weights=[5,3,2,2,1])[0]
            rating = random.randint(1,5) if act == "rate" else ""
            w.writerow([i+1, uid, mid, act, rating])
    print(f"데이터셋 생성 완료: {n}개 레코드 → {filename}")


# ══════════════════════════════════════════════════════════════════════
# 블룸 필터 (Bloom Filter)
# ══════════════════════════════════════════════════════════════════════
class BloomFilter:
    """
    확률적 집합(Set) 포함 여부 확인 자료구조
    - False Negative(거짓 음성): 절대 발생하지 않음
    - False Positive(거짓 양성): 발생 가능 (크기와 해시 함수 수에 따라 결정)
    - 메모리 복잡도: O(size) 비트
    """
    def __init__(self, size: int, num_hashes: int):
        self.size       = size
        self.num_hashes = num_hashes
        self.bit_array  = bytearray(size)   # 슬롯당 1바이트 사용
        self.count      = 0

    def _hashes(self, item):
        """num_hashes 개의 독립적인 해시값 생성"""
        item = str(item).encode()
        for i in range(self.num_hashes):
            h = int(hashlib.md5(item + i.to_bytes(2, 'big')).hexdigest(), 16)
            yield h % self.size

    def add(self, item):
        """항목 삽입"""
        for h in self._hashes(item):
            self.bit_array[h] = 1
        self.count += 1

    def __contains__(self, item):
        """조회: True → 존재할 가능성 있음 / False → 확실히 존재하지 않음"""
        return all(self.bit_array[h] for h in self._hashes(item))

    def memory_bytes(self) -> int:
        return sys.getsizeof(self.bit_array)

    @staticmethod
    def optimal_k(m: int, n: int) -> int:
        """이론적으로 최적의 해시 함수 개수 계산"""
        return max(1, round((m / n) * math.log(2)))

    @staticmethod
    def expected_fpr(m: int, k: int, n: int) -> float:
        """이론적 False Positive Rate 계산"""
        return (1 - math.exp(-k * n / m)) ** k


# ══════════════════════════════════════════════════════════════════════
# 카운트-민 스케치 (Count-Min Sketch)
# ══════════════════════════════════════════════════════════════════════
class CountMinSketch:
    """
    확률적 빈도 추정 자료구조
    - 실제 값보다 작게 추정하지 않음 (과대 추정만 가능)
    - 오차 보장:
      P(estimate > true + eps*N) < delta
      여기서 eps = e/width, delta = (1/e)^depth
    - 메모리 복잡도: O(width * depth) 정수
    """
    def __init__(self, width: int, depth: int):
        self.width = width
        self.depth = depth
        self.table = [[0] * width for _ in range(depth)]
        self.seeds = [random.randint(0, 2**31) for _ in range(depth)]
        self.total = 0

    def _hashes(self, item):
        """depth 개의 독립적인 해시값 생성"""
        item = str(item).encode()
        for i, seed in enumerate(self.seeds):
            h = int(hashlib.md5(item + seed.to_bytes(4, 'big')).hexdigest(), 16)
            yield h % self.width

    def add(self, item, count: int = 1):
        """항목 빈도 증가"""
        for i, h in enumerate(self._hashes(item)):
            self.table[i][h] += count
        self.total += count

    def query(self, item) -> int:
        """항목 빈도 추정값 반환 (각 행의 최소값 사용)"""
        return min(self.table[i][h] for i, h in enumerate(self._hashes(item)))

    def memory_bytes(self) -> int:
        return sys.getsizeof(self.table) + self.depth * self.width * 8

    def error_bound(self) -> float:
        """이론적 오차 상한 계산"""
        return math.e * self.total / self.width


# ══════════════════════════════════════════════════════════════════════
# 실제 정답(Ground Truth) 계산
# ══════════════════════════════════════════════════════════════════════
def compute_ground_truth(filename="events.csv"):
    true_set  = set()
    true_freq = defaultdict(int)
    total     = 0

    t0 = time.perf_counter()
    with open(filename) as f:
        for row in csv.DictReader(f):
            true_set.add(row["user_id"])
            true_set.add(row["movie_id"])
            true_freq[row["movie_id"]] += 1
            total += 1
    elapsed = time.perf_counter() - t0

    mem = sys.getsizeof(true_set) + sum(
        sys.getsizeof(k) + sys.getsizeof(v) for k, v in true_freq.items()
    )
    return true_set, true_freq, total, elapsed, mem


# ══════════════════════════════════════════════════════════════════════
# 실험 실행 함수
# ══════════════════════════════════════════════════════════════════════
def run_bloom_filter_experiments(filename, true_set, total_rows):
    print("\n=== 블룸 필터 실험 ===")
    configs = [(50_000, 3), (100_000, 4), (200_000, 5), (500_000, 7)]
    results = []

    # 질의 데이터 구성: 실제 존재 항목 500개 + 존재하지 않는 항목 500개
    pos_samples = random.sample(sorted(true_set), 500)
    neg_samples = [f"fake_item_{i}" for i in range(500)]
    query_items  = pos_samples + neg_samples
    query_labels = [True] * 500 + [False] * 500

    for size, nhash in configs:
        bf = BloomFilter(size, nhash)

        t0 = time.perf_counter()
        with open(filename) as f:
            for row in csv.DictReader(f):
                bf.add(row["user_id"])
                bf.add(row["movie_id"])
        elapsed = time.perf_counter() - t0

        tp = fp = tn = fn = 0

        for item, label in zip(query_items, query_labels):
            pred = item in bf

            if label and pred:
                tp += 1
            elif label and not pred:
                fn += 1
            elif not label and pred:
                fp += 1
            else:
                tn += 1

        fpr  = fp / (fp + tn) if (fp + tn) > 0 else 0
        mem  = bf.memory_bytes()
        tput = total_rows / elapsed

        row = dict(
            size=size,
            nhash=nhash,
            tp=tp,
            fp=fp,
            fn=fn,
            tn=tn,
            fpr=fpr,
            mem_kb=mem / 1024,
            time=elapsed,
            throughput=tput
        )

        results.append(row)

        print(
            f"  size={size:>7}, k={nhash}: "
            f"FPR={fpr:.4f} "
            f"mem={mem/1024:.0f}KB "
            f"time={elapsed:.3f}s "
            f"tput={tput:.0f}/s"
        )

    return results


def run_cms_experiments(filename, true_freq, total_rows):
    print("\n=== Count-Min Sketch 실험 ===")

    configs = [(500, 3), (1000, 4), (2000, 5), (5000, 7)]
    top_movies = sorted(true_freq.items(), key=lambda x: -x[1])[:100]

    results = []

    for width, depth in configs:
        cms = CountMinSketch(width, depth)

        t0 = time.perf_counter()

        with open(filename) as f:
            for row in csv.DictReader(f):
                cms.add(row["movie_id"])

        elapsed = time.perf_counter() - t0

        errors = [
            abs(cms.query(mid) - cnt) / cnt
            for mid, cnt in top_movies
        ]

        mean_err = sum(errors) / len(errors)
        max_err  = max(errors)
        mem      = cms.memory_bytes()
        tput     = total_rows / elapsed

        row = dict(
            width=width,
            depth=depth,
            mean_rel_err=mean_err,
            max_rel_err=max_err,
            mem_kb=mem / 1024,
            time=elapsed,
            throughput=tput
        )

        results.append(row)

        print(
            f"  w={width:>5}, d={depth}: "
            f"mean_err={mean_err:.4f} "
            f"max_err={max_err:.4f} "
            f"mem={mem/1024:.0f}KB "
            f"time={elapsed:.3f}s "
            f"tput={tput:.0f}/s"
        )

    return results


# ══════════════════════════════════════════════════════════════════════
# 메인 실행부
# ══════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    import os

    filename = "events.csv"

    if not os.path.exists(filename):
        generate_dataset(filename)

    print("실제 정답(Ground Truth) 계산 중...")

    true_set, true_freq, total_rows, gt_time, gt_mem = compute_ground_truth(filename)

    print(
        f"  rows={total_rows}, "
        f"unique={len(true_set)}, "
        f"time={gt_time:.3f}s, "
        f"mem≈{gt_mem/1024:.0f}KB"
    )

    bf_results  = run_bloom_filter_experiments(
        filename, true_set, total_rows
    )

    cms_results = run_cms_experiments(
        filename, true_freq, total_rows
    )

    # 결과 저장
    all_results = {
        "ground_truth": {
            "total_rows": total_rows,
            "unique_elements": len(true_set),
            "time_s": gt_time,
            "mem_kb": gt_mem / 1024,
        },
        "bloom_filter": bf_results,
        "count_min_sketch": cms_results,
    }

    with open("results.json", "w") as f:
        json.dump(all_results, f, indent=2, default=str)

    print("\n모든 실험 완료. 결과가 results.json 파일에 저장되었습니다.")