# -*- coding: utf-8 -*-
"""특성공학 파이프라인 구현 및 성능비교실험.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MyTrVD1Fyj47yTtijQjw2ScjI2jLJmRv

## 실제 데이터를 활용하여 머신러닝 성능 향상을 위한 특성공학 파이프라인 설계

전처리 및 변수 선택 전략에 따른 성능 차이를 비교,분석하는 것을 목표로한다.
데이터 탐색부터 결측치 처리, 인코딩, 스케일링, 변수 선택, 모델 학습 및 평가까지 전체  ML Pipeline을 직접 구현해야함
"""

# ============================================================
# Titanic Dataset (Google Colab / Kaggle 인증 불필요)
# ============================================================

import pandas as pd
import numpy as np

# 데이터 불러오기
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
train_df = pd.read_csv(url)

# ============================================================
# 데이터 확인
# ============================================================

print("=" * 60)
print("Dataset Shape")
print(train_df.shape)

print("\n" + "=" * 60)
print("First 5 Rows")
display(train_df.head())

print("\n" + "=" * 60)
print("Column Names")
print(train_df.columns.tolist())

print("\n" + "=" * 60)
print("Dataset Info")
train_df.info()

print("\n" + "=" * 60)
print("Missing Values")
print(train_df.isnull().sum())

print("\n" + "=" * 60)
print("Target Distribution (Survived)")
print(train_df["Survived"].value_counts())

print("\n" + "=" * 60)
print("Target Ratio (%)")
print(round(train_df["Survived"].value_counts(normalize=True) * 100, 2))

print("\n" + "=" * 60)
print("Statistical Summary")
display(train_df.describe(include="all"))

# ============================================================
# 머신러닝용 데이터 분리
# ============================================================

X = train_df.drop("Survived", axis=1)
y = train_df["Survived"]

print("\n" + "=" * 60)
print("Feature Shape:", X.shape)
print("Target Shape :", y.shape)

# ============================================================
# 결측치 현황
# ============================================================

missing_df = pd.DataFrame({
    "Missing Count": train_df.isnull().sum(),
    "Missing Ratio(%)": round(train_df.isnull().mean() * 100, 2)
})

print("\n" + "=" * 60)
print("Missing Value Report")
display(missing_df.sort_values("Missing Count", ascending=False))

# ============================================================
# 간단한 시각화
# ============================================================

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,4))
sns.countplot(data=train_df, x="Survived")
plt.title("Survival Distribution")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(data=train_df, x="Sex", hue="Survived")
plt.title("Survival by Sex")
plt.show()

plt.figure(figsize=(8,4))
sns.histplot(data=train_df, x="Age", hue="Survived", bins=30, kde=True)
plt.title("Age Distribution by Survival")
plt.show()

print("\n데이터 로딩 완료!")

"""
Feature Engineering Pipeline — Titanic Survival Prediction
ML Assignment: STEP 01~05
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler, RobustScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, roc_auc_score)
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

# ─────────────────────────────────────────────────────────────
# STEP 01. 데이터 준비
# ─────────────────────────────────────────────────────────────

!pip install -q xgboost

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

print("Shape:", df.shape)
print(df.describe())
print("\nMissing values:\n", df.isnull().sum())

# ─────────────────────────────────────────────────────────────
# STEP 02. EDA
# ─────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
df['Survived'].value_counts().plot(kind='bar', ax=axes[0], title='Target Distribution')
df.isnull().sum()[df.isnull().sum()>0].plot(kind='barh', ax=axes[1], title='Missing Values')
plt.tight_layout(); plt.savefig('eda_overview.png', dpi=120); plt.close()

fig, axes = plt.subplots(2, 3, figsize=(14, 8))
for i, col in enumerate(['Age','Fare','SibSp','Parch','Pclass']):
    axes[i//3][i%3].hist(df[col].dropna(), bins=20)
    axes[i//3][i%3].set_title(col)
plt.tight_layout(); plt.savefig('eda_hist.png', dpi=120); plt.close()

fig, axes = plt.subplots(1, 3, figsize=(13, 4))
for ax, col in zip(axes, ['Age', 'Fare', 'Pclass']):
    data = [df[df['Survived']==0][col].dropna(), df[df['Survived']==1][col].dropna()]
    ax.boxplot(data, labels=['Died','Survived']); ax.set_title(col)
plt.tight_layout(); plt.savefig('eda_boxplot.png', dpi=120); plt.close()

corr = df[['Survived','Pclass','Age','SibSp','Parch','Fare']].corr()
plt.figure(figsize=(7,5)); sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm')
plt.title('Correlation Heatmap'); plt.tight_layout(); plt.savefig('eda_heatmap.png', dpi=120); plt.close()

# ─────────────────────────────────────────────────────────────
# STEP 03. Feature Engineering
# ─────────────────────────────────────────────────────────────
def engineer_features(df):
    d = df.copy()
    # Derived feature 1: FamilySize
    d['FamilySize'] = d['SibSp'] + d['Parch'] + 1
    # Derived feature 2: IsAlone
    d['IsAlone'] = (d['FamilySize'] == 1).astype(int)
    # Derived feature 3: AgeGroup (구간 분류)
    d['AgeGroup'] = pd.cut(d['Age'].fillna(d['Age'].median()),
                            bins=[0,12,18,35,60,100], labels=[0,1,2,3,4]).astype(int)
    # Derived feature 4: FarePerPerson
    d['FarePerPerson'] = d['Fare'] / d['FamilySize']
    # Derived feature 5: Title (호칭 추출)
    d['Title'] = d['Name'].str.extract(r' ([A-Za-z]+)\.', expand=False)
    d['Title'] = d['Title'].replace(
        ['Lady','Countess','Capt','Col','Don','Dr','Major','Rev','Sir','Jonkheer','Dona'], 'Rare')
    d['Title'] = d['Title'].replace({'Mlle':'Miss','Ms':'Miss','Mme':'Mrs'})
    return d


def prepare_experiment(df, missing='mean', encoding='onehot', scaling='standard', feat_sel=False):
    d = engineer_features(df).copy()
    d = d.drop(columns=['PassengerId','Name','Ticket','Cabin'], errors='ignore')
    target = d['Survived']; d = d.drop(columns=['Survived'])
    num_cols = d.select_dtypes(include='number').columns.tolist()
    cat_cols = d.select_dtypes(include='object').columns.tolist()

    # 결측치 처리
    strategy_map = {'mean':'mean','median':'median','most_frequent':'most_frequent'}
    if missing in strategy_map:
        d[num_cols] = SimpleImputer(strategy=strategy_map[missing]).fit_transform(d[num_cols])
        d[cat_cols] = SimpleImputer(strategy='most_frequent').fit_transform(d[cat_cols])
    else:
        d = d.dropna(); target = target[d.index]

    # 인코딩
    if encoding == 'onehot':
        d = pd.get_dummies(d, columns=cat_cols, drop_first=True)
    else:
        le = LabelEncoder()
        for col in cat_cols:
            d[col] = le.fit_transform(d[col].astype(str))

    # 스케일링
    num_cols2 = d.select_dtypes(include='number').columns.tolist()
    scaler_map = {'standard': StandardScaler(), 'minmax': MinMaxScaler(), 'robust': RobustScaler()}
    if scaling in scaler_map:
        d[num_cols2] = scaler_map[scaling].fit_transform(d[num_cols2])

    X, y = d, target.reset_index(drop=True)

    # 변수 선택
    if feat_sel:
        sel = SelectKBest(f_classif, k=min(10, X.shape[1]))
        X = pd.DataFrame(sel.fit_transform(X, y), columns=X.columns[sel.get_support()])

    return X, y

# ─────────────────────────────────────────────────────────────
# STEP 04. Feature Selection (Feature Importance 시각화)
# ─────────────────────────────────────────────────────────────
X_fi, y_fi = prepare_experiment(df, missing='mean', encoding='onehot', scaling='standard')
rf_fi = RandomForestClassifier(n_estimators=200, random_state=42).fit(X_fi, y_fi)
fi = pd.Series(rf_fi.feature_importances_, index=X_fi.columns).sort_values(ascending=True).tail(15)
fi.plot(kind='barh', figsize=(9,6), title='RF Feature Importance (Top 15)')
plt.tight_layout(); plt.savefig('feature_importance.png', dpi=120); plt.close()
print("Top 5 features:\n", fi.tail(5).sort_values(ascending=False))

# ─────────────────────────────────────────────────────────────
# STEP 05. 모델 학습 및 평가
# ─────────────────────────────────────────────────────────────
models = {
    'LogisticReg':  LogisticRegression(max_iter=1000, random_state=42),
    'RandomForest': RandomForestClassifier(n_estimators=100, random_state=42),
    'XGBoost':      xgb.XGBClassifier(eval_metric='logloss', random_state=42, verbosity=0),
}

experiments = {
    'Base':  dict(missing='mean',          encoding='onehot', scaling=None,       feat_sel=False),
    'Exp-1': dict(missing='mean',          encoding='onehot', scaling='standard', feat_sel=False),
    'Exp-2': dict(missing='median',        encoding='label',  scaling='minmax',   feat_sel=True),
    'Exp-3': dict(missing='most_frequent', encoding='onehot', scaling='robust',   feat_sel=True),
}

print(f"\n{'실험':<8} {'모델':<15} {'Acc':>6} {'Prec':>6} {'Rec':>6} {'F1':>6} {'AUC':>6}")
print("-" * 60)
for exp_name, cfg in experiments.items():
    X, y = prepare_experiment(df, **cfg)
    X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
    for m_name, model in models.items():
        model.fit(X_tr, y_tr)
        yp = model.predict(X_te)
        yp_prob = model.predict_proba(X_te)[:,1]
        print(f"{exp_name:<8} {m_name:<15} "
              f"{accuracy_score(y_te,yp):>6.4f} "
              f"{precision_score(y_te,yp,zero_division=0):>6.4f} "
              f"{recall_score(y_te,yp,zero_division=0):>6.4f} "
              f"{f1_score(y_te,yp,zero_division=0):>6.4f} "
              f"{roc_auc_score(y_te,yp_prob):>6.4f}")